name: Deploy Parques Service

on:
  push:
    branches: [feature/despliegue]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/azar-parques:latest

      - name: Deploy en EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker system prune -af --volumes
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/azar-parques:latest
            docker stop azar-parques || true
            docker rm azar-parques || true
            docker run -d \
              --name azar-parques \
              --network host \
              -e SERVER_PORT=8086 \
              --restart unless-stopped \
              ${{ secrets.DOCKERHUB_USERNAME }}/azar-parques:latest